Algoritmo "excel"
// Disciplina  :  [Programaçao]
// Professor   : Cinthia
// Descrição   : Sequencia  de valores digitado pelo usuario
// Autor(a)    : Kaio Mesquita Da Silva
// Data atual  : 15/09/2020
Var
ini, final, cont: inteiro


Inicio

//entrada de dados
escreval("digite o valor inicial do contador")
leia(ini)
escreval("digite o valor final do contador")
leia(final)

//laco
para cont de ini ate final faca
 escreval (cont,".")
 fimpara


Fimalgoritmo