Algoritmo "tabuada"
// Disciplina  :  [Programação]
// Professor   :
// Descrição   : tabuada
// Autor(a)    : Kaio Mesquita Da Silva
// Data atual  : 15/09/2020
Var
num, resul, cont: inteiro



Inicio
// entrada
escreval("digite um valor para montar a tabuada")
leia(num)

para cont de 1 ate 10 faca
 resul<- num * cont
 escreval(num, " X ", cont, " = ", resul )
 fimpara

Fimalgoritmo